.TH "CryptNET Margin Calculator" 1
.SH NAME
<margincalc> \- A margin requirement calculator
.SH SYNOPSIS
.B margincalc
[options]

options: [-h] [--help] [--version]
.SH DESCRIPTION
.B margincalc

estimates margin required for option contract trades.

.SH OPTIONS
.TP
.B \-h
Displays help text.
.TP
.B \-v
Display program version information.
.TP
.B \-\-version
Display program version information.
.TP
.B \-\-help
Display help text.
.SH "SEE ALSO"
passwd(1) passgen.conf(5)
.SH BUGS
There are no known bugs.

